# Generated by Django 4.2.25 on 2025-10-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Validation Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.validationlevel', verbose_name='Parent Validation')),
            ],
            options={
                'verbose_name': 'Validation Level',
                'verbose_name_plural': 'Validation Levels',
            },
        ),
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.fieldactivity', verbose_name='Parent Activity')),
            ],
            options={
                'verbose_name': 'Field Activity',
                'verbose_name_plural': 'Field Activities',
            },
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('last_purchase', models.DateField(blank=True, null=True, verbose_name='Last Purchase')),
                ('purchase_satisfaction', models.BooleanField(blank=True, default=False, verbose_name='Purchase Satisfaction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_reports', to='crm.fieldactivity', verbose_name='Field of Activity')),
                ('validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.validationlevel', verbose_name='Validation Level')),
            ],
            options={
                'verbose_name': 'Call Report',
                'verbose_name_plural': 'Call Reports',
                'ordering': ['-number'],
            },
        ),
    ]
