# Generated by Django 4.2.25 on 2025-12-01 09:31

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('last_purchase', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Last Purchase')),
                ('purchase_satisfaction', models.BooleanField(blank=True, default=False, verbose_name='Purchase Satisfaction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Report',
                'verbose_name_plural': 'Call Reports',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('market_place', 'MarketPlace'), ('market_outside', 'MarketOutside'), ('quota', 'Quota'), ('overhead', 'Overhead')], default='market_place', max_length=20, verbose_name='Purchase type')),
                ('market_place_type', models.CharField(blank=True, choices=[('agreement', 'Agreement'), ('cash', 'Cash')], max_length=20, null=True, verbose_name='MarketPlace Type')),
                ('yekta_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yekta Code')),
                ('market_outside_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Market Outside Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('market_outside_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Outside Number')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer Name')),
                ('overhead_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Overhead Address')),
                ('overhead_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Overhead Number')),
                ('agreement_kotazh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agreement Kotazh')),
                ('cash_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash User')),
                ('cash_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash Password')),
                ('cash_kotazh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash Kotazh')),
                ('destination_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination Name')),
                ('quota_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quota Number')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, null=True, verbose_name='Updated At')),
                ('call_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_process', to='crm.callreport', verbose_name='Call Report')),
            ],
            options={
                'verbose_name': 'Purchase Process',
                'verbose_name_plural': 'Purchase Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Validation Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.validationlevel', verbose_name='Parent Validation')),
            ],
            options={
                'verbose_name': 'Validation Level',
                'verbose_name_plural': 'Validation Levels',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Transaction Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'Transaction Type Level',
                'verbose_name_plural': 'Transaction Type Levels',
            },
        ),
        migrations.CreateModel(
            name='SupplyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Supply Status')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.supplystatus', verbose_name='Parent Supply Status')),
            ],
            options={
                'verbose_name': 'Supply Status Level',
                'verbose_name_plural': 'Supply Status Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('market_place', 'MarketPlace'), ('market_outside', 'MarketOutside'), ('quota', 'Quota'), ('overhead', 'Overhead')], max_length=20, verbose_name='Sale Type')),
                ('sale_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Sale Date')),
                ('purchase_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_report', to='crm.purchaseprocess', verbose_name='Purchase Process')),
            ],
            options={
                'verbose_name': 'Sale Report',
                'verbose_name_plural': 'Sale Reports',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='Quota Supply Status Level')),
            ],
            options={
                'verbose_name': 'Quota Sale',
                'verbose_name_plural': 'Quota Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Type Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.producttype', verbose_name='Parent Product Type')),
            ],
            options={
                'verbose_name': 'Product Type Level',
                'verbose_name_plural': 'Product Type Levels',
            },
        ),
        migrations.CreateModel(
            name='PortName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Port Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.portname', verbose_name='Parent Port Name')),
            ],
            options={
                'verbose_name': 'Port Name Level',
                'verbose_name_plural': 'Port Name Levels',
            },
        ),
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overhead', to='crm.salereport', verbose_name='Sale Report')),
            ],
            options={
                'verbose_name': 'Overhead Sale',
                'verbose_name_plural': 'Overhead Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('market_price', models.IntegerField(blank=True, null=True, verbose_name='Market Price')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit')),
                ('unofficial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Unofficial')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight_barname', models.IntegerField(blank=True, null=True, verbose_name='Weight Barname')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='MarketPlace Supply Status Level')),
            ],
            options={
                'verbose_name': 'MarketPlace Sale',
                'verbose_name_plural': 'MarketPlace Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight_barname', models.IntegerField(blank=True, null=True, verbose_name='Weight Barname')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketoutside', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='MarketOutside Supply Status Level')),
            ],
            options={
                'verbose_name': 'Market Outside Sale',
                'verbose_name_plural': 'Market Outside Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoadingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loading Time')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.loadingtime', verbose_name='Parent Loading Time')),
            ],
            options={
                'verbose_name': 'Loading Time Level',
                'verbose_name_plural': 'Loading Time Levels',
            },
        ),
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.fieldactivity', verbose_name='Parent Activity')),
            ],
            options={
                'verbose_name': 'Field Activity',
                'verbose_name_plural': 'Field Activities',
            },
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.countryname', verbose_name='Parent Country Name')),
            ],
            options={
                'verbose_name': 'Country Name Level',
                'verbose_name_plural': 'Country Name Levels',
            },
        ),
        migrations.CreateModel(
            name='CargoAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20, verbose_name='Load Type')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='number')),
                ('name_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='name company')),
                ('name_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='name ceo')),
                ('number_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='number ceo')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='sales expert name')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='product price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.countryname', verbose_name='Country Name')),
                ('loading_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.loadingtime', verbose_name='Loading Time')),
                ('port_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.portname', verbose_name='Port Name')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.producttype', verbose_name='Product Type')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'CargoAnnouncement',
                'verbose_name_plural': 'CargoAnnouncement',
            },
        ),
        migrations.AddField(
            model_name='callreport',
            name='field_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_reports', to='crm.fieldactivity', verbose_name='Field of Activity'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.validationlevel', verbose_name='Validation Level'),
        ),
    ]
