# Generated by Django 4.2.25 on 2025-10-12 12:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='last_purchase',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Last Purchase'),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='updated_at',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Type Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.producttype', verbose_name='Parent Product Type')),
            ],
            options={
                'verbose_name': 'Product Type Level',
                'verbose_name_plural': 'Product Type Levels',
            },
        ),
        migrations.CreateModel(
            name='CargoAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20, verbose_name='Load Type')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full name')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('name_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='name company')),
                ('name_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='name ceo')),
                ('number_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='number ceo')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Load Announcement',
                'verbose_name_plural': 'Load Announcements',
            },
        ),
    ]
