# Generated by Django 4.2.25 on 2025-10-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_callreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoannouncement',
            options={'verbose_name': 'Cargo Announcement', 'verbose_name_plural': 'Cargo Announcement'},
        ),
    ]
