# Generated by Django 4.2.25 on 2025-10-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_cargoannouncement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoannouncement',
            options={'verbose_name': 'CargoAnnouncement', 'verbose_name_plural': 'CargoAnnouncement'},
        ),
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.brandname', verbose_name='Parent Brand Name Type')),
            ],
            options={
                'verbose_name': 'Brand Name Level',
                'verbose_name_plural': 'Brand Name Levels',
            },
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.brandname', verbose_name='Brand Name'),
        ),
    ]
