# Generated by Django 4.2.25 on 2025-10-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cargoannouncement_options_brandname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandName',
            new_name='PortName',
        ),
        migrations.RemoveField(
            model_name='cargoannouncement',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='port_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.portname', verbose_name='Port Name'),
        ),
    ]
