# Generated by Django 4.2.25 on 2025-10-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_brandname_portname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portname',
            options={'verbose_name': 'Port Name Level', 'verbose_name_plural': 'Port Name Levels'},
        ),
        migrations.AlterField(
            model_name='portname',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Port Name'),
        ),
        migrations.AlterField(
            model_name='portname',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.portname', verbose_name='Parent Port Name'),
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.countryname', verbose_name='Parent Country Name')),
            ],
            options={
                'verbose_name': 'Country Name Level',
                'verbose_name_plural': 'Country Name Levels',
            },
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.countryname', verbose_name='Country Name'),
        ),
    ]
