# Generated by Django 4.2.25 on 2025-10-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_portname_options_alter_portname_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loading Time')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.loadingtime', verbose_name='Parent Loading Time')),
            ],
            options={
                'verbose_name': 'Loading Time Level',
                'verbose_name_plural': 'Loading Time Levels',
            },
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='loading_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.loadingtime', verbose_name='Loading Time'),
        ),
    ]
