# Generated by Django 4.2.25 on 2025-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_salereport_options_alter_salereport_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoannouncement',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='number'),
        ),
    ]
