# Generated by Django 4.2.25 on 2025-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_cargoannouncement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketoutside',
            name='account_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining'),
        ),
        migrations.AlterField(
            model_name='marketoutside',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='account_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='unofficial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Unofficial'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='account_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Account Remaining'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
    ]
