# Generated by Django 4.2.25 on 2025-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_marketoutside_account_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit'),
        ),
    ]
