FROM python:3.10-slim-bullseye

LABEL maintainer="programmer.amirrezaattary@gmail.com"


ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    gettext \
    gettext-base \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./core .

