# Generated by Django 4.2.25 on 2025-11-12 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='تصویر خبر')),
                ('content', models.TextField(verbose_name='متن کامل خبر')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('tags', models.CharField(help_text='تگ\u200cها را با کاما جدا کنید', max_length=200, verbose_name='تگ\u200cها')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganicProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا')),
                ('product_title', models.TextField(verbose_name='عنوان کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'محصولات ارگانیک',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('product_price', models.IntegerField(verbose_name='قیمت کالا')),
                ('product_description', models.TextField(verbose_name='توضیحات کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('product_photo', models.ImageField(blank=True, default='/Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا نهاد های دام',
            },
        ),
    ]
