# Generated by Django 4.2.25 on 2025-12-03 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFeedKhoshab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'خوراک دام خوشاب',
            },
        ),
        migrations.CreateModel(
            name='AnimalRefinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'پالیشگاه دام',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('crate_deta', models.DateField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('job', models.CharField(choices=[('آزاد', 'آزاد'), ('بیکار', 'بیکار'), ('کارمند', 'کارمند'), ('بازنشسته', 'بازنشسته'), ('دیگر مشاغل', 'دیگر مشاغل')], max_length=50, verbose_name='شغل')),
                ('capital', models.CharField(choices=[('کمتر از 200 میلیون تومان', 'کمتر از 200 میلیون تومان'), ('بین 200 تا 500 میلیون تومان', 'بین 200 تا 500 میلیون تومان'), ('بین 500 میلیون تومان تا یک میلیارد تومان', 'بین 500 میلیون تومان تا یک میلیارد تومان'), ('بیشتر از یک میلیارد تومان', 'بیشتر از یک میلیارد تومان')], max_length=100, verbose_name='میزان سرمایه')),
                ('message', models.TextField(verbose_name='پیام مورد نظر')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
        ),
        migrations.CreateModel(
            name='layingHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'مجموعه مرغ تخم گذار',
            },
        ),
        migrations.CreateModel(
            name='MotherChickenFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'مزرعه مرغ مادر',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='تصویر خبر')),
                ('content', models.TextField(verbose_name='متن کامل خبر')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('tags', models.CharField(help_text='تگ\u200cها را با کاما جدا کنید', max_length=200, verbose_name='تگ\u200cها')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganicProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا')),
                ('product_title', models.TextField(verbose_name='عنوان کالا')),
                ('product_price', models.IntegerField(default=0, verbose_name='قیمت کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'محصولات ارگانیک',
            },
        ),
        migrations.CreateModel(
            name='PlantRefinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'پالیشگاه گیاهان دارویی',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('product_price', models.IntegerField(verbose_name='قیمت کالا')),
                ('product_description', models.TextField(verbose_name='توضیحات کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا نهاد های دام',
            },
        ),
        migrations.CreateModel(
            name='SupplyingLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'تامبن نهاد های دامی',
            },
        ),
    ]
