# Generated by Django 4.2.25 on 2025-12-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalfeedkhoshab',
            options={'verbose_name': 'خوراک دام خوشاب'},
        ),
        migrations.AlterModelOptions(
            name='animalrefinery',
            options={'verbose_name': 'پالیشگاه دام'},
        ),
        migrations.AlterModelOptions(
            name='layinghen',
            options={'verbose_name': 'مجموعه مرغ تخم گذار'},
        ),
        migrations.AlterModelOptions(
            name='motherchickenfarm',
            options={'verbose_name': 'مزرعه مرغ مادر'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='organicproducts',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'محصولات ارگانیک'},
        ),
        migrations.AlterModelOptions(
            name='plantrefinery',
            options={'verbose_name': 'پالیشگاه گیاهان دارویی'},
        ),
        migrations.AlterModelOptions(
            name='purchaselivestock',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا نهاد های دام'},
        ),
        migrations.AlterModelOptions(
            name='supplyinglivestock',
            options={'verbose_name': 'تامبن نهاد های دامی'},
        ),
    ]
