# Generated by Django 4.2.25 on 2025-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicproducts',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='قیمت کالا'),
        ),
    ]
