# Generated by Django 4.2.25 on 2025-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfeedkhoshab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='animalrefinery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='layinghen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='motherchickenfarm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا'),
        ),
        migrations.AlterField(
            model_name='plantrefinery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا'),
        ),
        migrations.AlterField(
            model_name='supplyinglivestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
