# Generated by Django 4.2.25 on 2025-12-08 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_animalfeedkhoshab_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalfeedkhoshab',
            options={'verbose_name': 'Animal Feed Khoshab'},
        ),
        migrations.AlterModelOptions(
            name='animalrefinery',
            options={'verbose_name': 'Animal Refinery'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='layinghen',
            options={'verbose_name': 'Laying Hen'},
        ),
        migrations.AlterModelOptions(
            name='motherchickenfarm',
            options={'verbose_name': 'Mother Chicken Farm'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='organicproducts',
            options={'verbose_name': 'product', 'verbose_name_plural': 'organic products'},
        ),
        migrations.AlterModelOptions(
            name='plantrefinery',
            options={'verbose_name': 'Plant Refinery'},
        ),
        migrations.AlterModelOptions(
            name='purchaselivestock',
            options={'verbose_name': 'product', 'verbose_name_plural': 'purchase livestock products'},
        ),
        migrations.AlterModelOptions(
            name='supplyinglivestock',
            options={'verbose_name': 'Supplying Livestock'},
        ),
        migrations.AlterField(
            model_name='animalfeedkhoshab',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='animalfeedkhoshab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='animalfeedkhoshab',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='animalrefinery',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='animalrefinery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='animalrefinery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='crate_deta',
            field=models.DateField(auto_now_add=True, verbose_name='sent time'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=11, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='capital',
            field=models.CharField(choices=[('کمتر از 200 میلیون تومان', 'کمتر از 200 میلیون تومان'), ('بین 200 تا 500 میلیون تومان', 'بین 200 تا 500 میلیون تومان'), ('بین 500 میلیون تومان تا یک میلیارد تومان', 'بین 500 میلیون تومان تا یک میلیارد تومان'), ('بیشتر از یک میلیارد تومان', 'بیشتر از یک میلیارد تومان')], max_length=100, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='sent time'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='job',
            field=models.CharField(choices=[('آزاد', 'آزاد'), ('بیکار', 'بیکار'), ('کارمند', 'کارمند'), ('بازنشسته', 'بازنشسته'), ('دیگر مشاغل', 'دیگر مشاغل')], max_length=50, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='number',
            field=models.CharField(max_length=20, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='layinghen',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='layinghen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='layinghen',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='motherchickenfarm',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='motherchickenfarm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='motherchickenfarm',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(help_text='Separate tags with commas', max_length=200, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product photo'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_title',
            field=models.TextField(verbose_name='product title'),
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='plantrefinery',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plantrefinery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='plantrefinery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_description',
            field=models.TextField(verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product photo'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_price',
            field=models.IntegerField(verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='supplyinglivestock',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='supplyinglivestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='supplyinglivestock',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
