# Generated by Django 4.2.25 on 2025-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_organicproducts_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicproducts',
            name='product_photo',
            field=models.ImageField(blank=True, default='/Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس کالا'),
        ),
    ]
