# Generated by Django 4.2.25 on 2025-11-10 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_purchaselivestock_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا')),
                ('product_title', models.TextField(verbose_name='عنوان کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'محصولات ارگانیک',
            },
        ),
    ]
