# Generated by Django 4.2.25 on 2025-11-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('آزاد', 'آزاد'), ('بیکار', 'بیکار'), ('کارمند', 'کارمند'), ('بازنشسته', 'بازنشسته'), ('دیگر مشاغل', 'دیگر مشاغل')], max_length=50)),
                ('capital', models.CharField(choices=[('کمتر از 200 میلیون تومان', 'کمتر از 200 میلیون تومان'), ('بین 200 تا 500 میلیون تومان', 'بین 200 تا 500 میلیون تومان'), ('بین 500 میلیون تومان تا یک میلیارد تومان', 'بین 500 میلیون تومان تا یک میلیارد تومان'), ('بیشتر از یک میلیارد تومان', 'بیشتر از یک میلیارد تومان')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
