# Generated by Django 4.2.25 on 2025-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='capital',
            field=models.CharField(choices=[('کمتر از 200 میلیون تومان', 'کمتر از 200 میلیون تومان'), ('بین 200 تا 500 میلیون تومان', 'بین 200 تا 500 میلیون تومان'), ('بین 500 میلیون تومان تا یک میلیارد تومان', 'بین 500 میلیون تومان تا یک میلیارد تومان'), ('بیشتر از یک میلیارد تومان', 'بیشتر از یک میلیارد تومان')], max_length=100, verbose_name='میزان سرمایه'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='job',
            field=models.CharField(choices=[('آزاد', 'آزاد'), ('بیکار', 'بیکار'), ('کارمند', 'کارمند'), ('بازنشسته', 'بازنشسته'), ('دیگر مشاغل', 'دیگر مشاغل')], max_length=50, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(verbose_name='پیام مورد نظر'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
